### ISSUE TITLE
feature - ability to read input/metric/schema config from s3

### ISSUE THREAD

**Issue by tooptoop4** [YotpoLtd/metorikku#165] opened 2019-04-01 14:33 UTC
Looks like currently it expects all the config files to be on local disk rather than on s3.

Exception in thread "main" com.yotpo.metorikku.exceptions.MetorikkuException: Failed to parse config file
        at com.yotpo.metorikku.configuration.job.ConfigurationParser$.parse(ConfigurationParser.scala:38)
        at com.yotpo.metorikku.Metorikku$.delayedEndpoint$com$yotpo$metorikku$Metorikku$1(Metorikku.scala:10)
        at com.yotpo.metorikku.Metorikku$delayedInit$body.apply(Metorikku.scala:7)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.yotpo.metorikku.Metorikku$.main(Metorikku.scala:7)

Exception in thread "main" java.io.FileNotFoundException: No Files to Run s3a.......
        at com.yotpo.metorikku.utils.FileUtils$.getListOfFiles(FileUtils.scala:27)
        at com.yotpo.metorikku.metric.MetricSet.parseMetrics(MetricSet.scala:29)
        at com.yotpo.metorikku.metric.MetricSet.<init>(MetricSet.scala:25)
        at com.yotpo.metorikku.Metorikku$$anonfun$runMetrics$1.apply(Metorikku.scala:16)
        at com.yotpo.metorikku.Metorikku$$anonfun$runMetrics$1.apply(Metorikku.scala:15)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at com.yotpo.metorikku.Metorikku$.runMetrics(Metorikku.scala:15)
        at com.yotpo.metorikku.Metorikku$.delayedEndpoint$com$yotpo$metorikku$Metorikku$1(Metorikku.scala:11)

**Comment by lyogev** [comment] 2019-04-01 16:27
Duplicate of #142. Will be handled soon.

**Closed by lyogev** 2019-04-01 16:27 UTC
